
# Root directory of the photo tree:
root_dir = "/my/photos"

# Amount of time each slide is displayed (not including transitions), in seconds:
slide_display_time = 12

# Transition time, in seconds:
slide_transition_time = 2

# Maximum amount of time the slideshow will be left paused before it
# automatically resumes, in seconds:
max_pause_time = 3600

# Minimum photo rating (1-5) to show.
min_rating = 3

# Minimum age of photos to show, in days, or 0 for no limit.
min_days = 0

# Maximum age of photos to show, in days, or 0 for no limit.
max_days = 0

# Width of window, or 0 for full screen.
window_width = 0

# Height of window, or 0 for full screen.
window_height = 0

# Directories to skip altogether.
unwanted_dirs = [
    ".thumbnails",
    ".small",
    "Broken",
    "Private",
]

# Directory parts to not display in the label.
bad_parts = [
    "Published", "Originals", "Unsorted"
]

# If a pathname part has this prefix (case-sensitive), the whole part is ignored
# when displaying the label.
bad_file_prefixes = ["DSC_", "PICT", "100_", "IMG_", "P101", "VIP_", "Image",
        "pick", "dcp_", "DSCF"]

# 511.org configuration.
[511org]
token = ""
agency = "SF"
stop_code = "12345"

[party]
qr_code = "sms:4155555555" # Or http URL for web upload.
message = "Text photos to 415-555-5555"

# Fill this in if you want to be able to send photos to the slideshow program
# using text messages. Requires a Twilio account and phone number.
[twilio]
sid = ""                 # E.g., "ECbf..."
token = ""               # The secret token string.
subdir = "twilio"        # Where to store images, relative to root_dir.

[web]
subdir = "web"
hostname = "0.0.0.0"
port = 8080
